[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc_version = '0.8.20'
evm_version = 'paris'
fs_permissions = [
    { access = "read", path = "./test/"},
    { access = "read-write", path = "./test/"}
]
use_literal_content = true
optimizer = true
auto_detect_remappings = false

[invariant]
runs = 32
depth = 100
fail_on_revert = true

# See more config options https://book.getfoundry.sh/reference/config/
