[package]
name = "worker"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
async-trait = "0.1"
block_subscriber = { path = "../dispatcher-v2/block_subscriber"}
dispatcher = { path = "../dispatcher-v2/dispatcher"}
middleware_factory = { path = "../dispatcher-v2/middleware_factory"}
transaction_manager = { path = "../dispatcher-v2/transaction_manager"}
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "66a503d" }
ethabi = { version = "14.0.0", default-features = false }
futures = "0.3"
im = "15.0"
serde_json = "1.0"
snafu = "0.6"
tokio = { version = "^1", features = ["sync", "rt-multi-thread", "macros"] }

[build-dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "66a503d" }
serde_json = "1.0"
